# -*- coding: utf-8 -*-
"""HealthHelper AI: Intelligent Symptom Checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjIZLdhlM8DEtfMa15Ai5fB8JTe2kDmr
"""

!pip install streamlit faiss-cpu sentence-transformers transformers torch pyngrok

code = '''
import streamlit as st
import faiss
from sentence_transformers import SentenceTransformer
from transformers import T5Tokenizer, T5ForConditionalGeneration
import numpy as np
import torch

st.set_page_config(page_title="HealthHelper AI", page_icon="🩺")
st.title("🩺 HealthHelper: AI Symptom Checker")
st.markdown("Ask any health-related question and get real-time advice using AI.")

docs = [
    "Fever and body ache are common signs of flu or viral infection.",
    "Sneezing, runny nose, and watery eyes are symptoms of allergies or common cold.",
    "Fatigue, weight gain, and cold intolerance could be signs of hypothyroidism.",
    "High blood sugar, frequent urination, and excessive thirst may indicate diabetes.",
    "Shortness of breath, chest pain, and sweating could be signs of a heart attack.",
    "Persistent cough, blood in sputum, and weight loss may indicate tuberculosis.",
    "Joint pain, swelling, and stiffness might be due to rheumatoid arthritis.",
    "Headache, nausea, and light sensitivity could suggest migraine.",
    "Skin rash, fever, and swollen lymph nodes can indicate an autoimmune disease.",
    "Diarrhea, abdominal pain, and bloating could be signs of food poisoning or IBS.",
    "Sudden weakness on one side of the body, slurred speech, and confusion may indicate a stroke.",
    "Yellowing of skin and eyes, fatigue, and dark urine may suggest hepatitis.",
    "Increased heart rate, anxiety, and weight loss may be symptoms of hyperthyroidism.",
    "Frequent urination at night, blurry vision, and slow wound healing could indicate diabetes mellitus.",
    "Severe lower abdominal pain during menstruation may be a sign of endometriosis.",
    "Dry cough, fever, and loss of smell are key symptoms of COVID-19.",
    "Chest tightness, wheezing, and coughing may be signs of asthma.",
    "Sudden sharp pain in the lower right abdomen might indicate appendicitis.",
    "Pain during urination, frequent urge to urinate, and cloudy urine may indicate a UTI (urinary tract infection).",
    "Burning chest pain after meals, bloating, and acid reflux suggest GERD.",
    "Itchy red skin, swelling, and blisters may be signs of eczema or contact dermatitis.",
    "Unexplained weight loss, fatigue, and night sweats may indicate cancer.",
    "Muscle weakness, double vision, and drooping eyelids are symptoms of myasthenia gravis.",
    "Tremors, slow movement, and stiff muscles are signs of Parkinson’s disease.",
    "High fever, stiff neck, and sensitivity to light could be meningitis.",
    "Back pain, fatigue, and numbness in legs may suggest a slipped disc or sciatica.",
    "Irregular heartbeat, dizziness, and chest discomfort could be a sign of arrhythmia.",
    "Swollen feet, fatigue, and breathlessness could point to congestive heart failure.",
    "Extreme thirst, frequent infections, and dry skin could suggest Type 2 Diabetes.",
    "Painful blisters around the lips or genitals might indicate herpes simplex infection.",
    "Craving non-food items and pale skin may be symptoms of iron deficiency anemia.",
    "Loss of taste/smell (anosmia) may be a sign of COVID-19.",
    "Pain behind the eyes, high fever, and a skin rash with white islands on a red background may indicate dengue fever.",
    "Rose-colored spots on the abdomen and step-ladder fever pattern may suggest typhoid.",
    "Recurring fever with chills every 48 to 72 hours may be a sign of malaria.",
    "Jaw stiffness and muscle spasms could be symptoms of tetanus.",
    "Fear of water and wind sensitivity along with confusion may indicate rabies.",
    "Dark-colored urine, yellow skin, and clay-colored stools may be signs of hepatitis A.",
    "Pill-rolling hand tremor, facial masking, and shuffling gait could point to Parkinson's disease.",
    "Sudden vision loss, electric shock sensation down the back, and limb weakness may suggest multiple sclerosis.",
    "Visual disturbances like zigzag lines or blind spots before a headache may indicate migraine with aura.",
    "Pre-seizure auras and confusion after convulsions are typical in epilepsy.",
    "Chest pain radiating to the left arm or jaw with a feeling of impending doom may indicate myocardial infarction.",
    "Severe limb pain, especially in children, and swollen fingers may suggest sickle cell disease.",
    "One-sided leg swelling and pain may indicate deep vein thrombosis (DVT).",
    "Increased hunger, urination, and thirst along with blurred vision may suggest diabetes.",
    "Bulging eyes and intolerance to heat could be signs of Graves' disease (hyperthyroidism).",
    "Darkened skin in gums and salt cravings may indicate Addison’s disease.",
    "Butterfly-shaped rash on the face and sensitivity to sunlight could suggest lupus (SLE).",
    "Morning stiffness lasting more than an hour and symmetrical joint pain are signs of rheumatoid arthritis.",
    "Chronic lower back pain that improves with activity and reduced spinal flexibility may indicate ankylosing spondylitis.",
    "Abdominal pain that improves with eating may point to duodenal ulcer, while pain that worsens with eating suggests gastric ulcer.",
    "Rebound tenderness and pain at McBurney's point are classic signs of appendicitis.",
    "Pain in the upper right abdomen after fatty meals and positive Murphy’s sign may indicate gallstones."
]

embedder = SentenceTransformer('all-MiniLM-L6-v2')
doc_embeddings = embedder.encode(docs, convert_to_numpy=True)
index = faiss.IndexFlatL2(doc_embeddings.shape[1])
index.add(doc_embeddings)

# Fixed: Using T5 model directly (more reliable)
tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-base")
model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-base")

def retrieve_context(query, k=2):
    query_embedding = embedder.encode([query], convert_to_numpy=True)
    _, I = index.search(query_embedding, k)
    return " ".join([docs[i] for i in I[0]])

def get_answer(context, question):
    prompt = f"""Answer the following question based on the context:

Context: {context}

Question: {question}"""

    inputs = tokenizer(prompt, return_tensors="pt", max_length=512, truncation=True)
    outputs = model.generate(
        inputs.input_ids,
        max_length=150,
        num_beams=4,
        early_stopping=True
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

user_input = st.text_input("🔍 Ask your health question:")

if user_input:
    with st.spinner("🤔 Thinking..."):
        context = retrieve_context(user_input)
        response = get_answer(context, user_input)

    st.subheader("💬 Answer:")
    st.success(response)

    with st.expander("🧠 Retrieved Knowledge Base Context"):
        st.write(context)

st.markdown("---")
st.markdown("⚠️ *This is not medical advice. Please consult a doctor for health concerns.*")
'''

with open("app.py", "w") as f:
    f.write(code)

print("✅ Full corrected app.py saved successfully!")

from pyngrok import ngrok
import os

# Kill any existing tunnels first
ngrok.kill()

# ================== PUT YOUR REAL TOKEN HERE ==================
!ngrok config add-authtoken 3GLWrZgiUeVBa8M3Ntx4JbdT35Q_5mUmwz7ZtBpmbdWWCtKxN
# ============================================================

public_url = ngrok.connect(8501)
print("🚀 Your App is Running at:", public_url)

# Run the Streamlit app
!streamlit run app.py

# Commented out IPython magic to ensure Python compatibility.
# !pip install faiss-cpu sentence-transformers transformers
# 
# 
# 
# 
# # Sample health info (can expand later)
# docs = [
#     "Fever is a common symptom of infections and usually indicates the body is fighting something.",
#     "Vitamin D deficiency symptoms include fatigue, depression, and bone pain.",
#     "A sore throat can be caused by a virus, bacteria, or allergies.",
#     "Drink plenty of fluids and rest when you have a cold or flu.",
#     "See a doctor if symptoms persist or worsen over time.",
# ]
# 
# 
# 
# 
# 
# from sentence_transformers import SentenceTransformer
# import faiss
# import numpy as np
# 
# embedder = SentenceTransformer('all-MiniLM-L6-v2')
# doc_embeddings = embedder.encode(docs, convert_to_numpy=True)
# 
# index = faiss.IndexFlatL2(doc_embeddings.shape[1])
# index.add(doc_embeddings)
# 
# def retrieve_context(query, k=2):
#     query_embedding = embedder.encode([query], convert_to_numpy=True)
#     _, I = index.search(query_embedding, k)
#     return " ".join([docs[i] for i in I[0]])
# 
# 
# 
# 
# 
# from transformers import pipeline
# 
# generator = pipeline("text2text-generation", model="google/flan-t5-base")
# 
# def get_answer(context, question):
#     prompt = f"Context: {context}\nQuestion: {question}"
#     return generator(prompt, max_length=100)[0]['generated_text']
# 
# 
# 
# 
# 
# query = "What are symptoms of vitamin D deficiency?"
# ctx = retrieve_context(query)
# get_answer(ctx, query)
# 
# 
# 
# 
# 
# pip install streamlit
# 
# 
# 
# 
#   code = '''
# import streamlit as st
# import faiss
# from sentence_transformers import SentenceTransformer
# from transformers import pipeline
# import numpy as np
# 
# st.set_page_config(page_title="HealthHelper AI", page_icon="🩺")
# st.title("🩺 HealthHelper: AI Symptom Checker")
# st.markdown("Ask any health-related question and get real-time advice using AI.")
# 
# docs = [
# 
#     "Fever and body ache are common signs of flu or viral infection.",
#     "Sneezing, runny nose, and watery eyes are symptoms of allergies or common cold.",
#     "Fatigue, weight gain, and cold intolerance could be signs of hypothyroidism.",
#     "High blood sugar, frequent urination, and excessive thirst may indicate diabetes.",
#     "Shortness of breath, chest pain, and sweating could be signs of a heart attack.",
#     "Persistent cough, blood in sputum, and weight loss may indicate tuberculosis.",
#     "Joint pain, swelling, and stiffness might be due to rheumatoid arthritis.",
#     "Headache, nausea, and light sensitivity could suggest migraine.",
#     "Skin rash, fever, and swollen lymph nodes can indicate an autoimmune disease.",
#     "Diarrhea, abdominal pain, and bloating could be signs of food poisoning or IBS.",
#     "Sudden weakness on one side of the body, slurred speech, and confusion may indicate a stroke.",
#     "Yellowing of skin and eyes, fatigue, and dark urine may suggest hepatitis.",
#     "Increased heart rate, anxiety, and weight loss may be symptoms of hyperthyroidism.",
#     "Frequent urination at night, blurry vision, and slow wound healing could indicate diabetes mellitus.",
#     "Severe lower abdominal pain during menstruation may be a sign of endometriosis.",
#     "Dry cough, fever, and loss of smell are key symptoms of COVID-19.",
#     "Chest tightness, wheezing, and coughing may be signs of asthma.",
#     "Sudden sharp pain in the lower right abdomen might indicate appendicitis.",
#     "Pain during urination, frequent urge to urinate, and cloudy urine may indicate a UTI (urinary tract infection).",
#     "Burning chest pain after meals, bloating, and acid reflux suggest GERD.",
#     "Itchy red skin, swelling, and blisters may be signs of eczema or contact dermatitis.",
#     "Unexplained weight loss, fatigue, and night sweats may indicate cancer.",
#     "Muscle weakness, double vision, and drooping eyelids are symptoms of myasthenia gravis.",
#     "Tremors, slow movement, and stiff muscles are signs of Parkinson’s disease.",
#     "High fever, stiff neck, and sensitivity to light could be meningitis.",
#     "Back pain, fatigue, and numbness in legs may suggest a slipped disc or sciatica.",
#     "Irregular heartbeat, dizziness, and chest discomfort could be a sign of arrhythmia.",
#     "Swollen feet, fatigue, and breathlessness could point to congestive heart failure.",
#     "Extreme thirst, frequent infections, and dry skin could suggest Type 2 Diabetes.",
#     "Painful blisters around the lips or genitals might indicate herpes simplex infection.",
#     "Craving non-food items and pale skin may be symptoms of iron deficiency anemia.",
#     "Loss of taste/smell (anosmia) may be a sign of COVID-19.",
#     "Pain behind the eyes, high fever, and a skin rash with white islands on a red background may indicate dengue fever.",
#     "Rose-colored spots on the abdomen and step-ladder fever pattern may suggest typhoid.",
#     "Recurring fever with chills every 48 to 72 hours may be a sign of malaria.",
#     "Jaw stiffness and muscle spasms could be symptoms of tetanus.",
#     "Fear of water and wind sensitivity along with confusion may indicate rabies.",
#     "Dark-colored urine, yellow skin, and clay-colored stools may be signs of hepatitis A.",
#     "Pill-rolling hand tremor, facial masking, and shuffling gait could point to Parkinson's disease.",
#     "Sudden vision loss, electric shock sensation down the back, and limb weakness may suggest multiple sclerosis.",
#     "Visual disturbances like zigzag lines or blind spots before a headache may indicate migraine with aura.",
#     "Pre-seizure auras and confusion after convulsions are typical in epilepsy.",
#     "Chest pain radiating to the left arm or jaw with a feeling of impending doom may indicate myocardial infarction.",
#     "Severe limb pain, especially in children, and swollen fingers may suggest sickle cell disease.",
#     "One-sided leg swelling and pain may indicate deep vein thrombosis (DVT).",
#     "Increased hunger, urination, and thirst along with blurred vision may suggest diabetes.",
#     "Bulging eyes and intolerance to heat could be signs of Graves' disease (hyperthyroidism).",
#     "Darkened skin in gums and salt cravings may indicate Addison’s disease.",
#     "Butterfly-shaped rash on the face and sensitivity to sunlight could suggest lupus (SLE).",
#     "Morning stiffness lasting more than an hour and symmetrical joint pain are signs of rheumatoid arthritis.",
#     "Chronic lower back pain that improves with activity and reduced spinal flexibility may indicate ankylosing spondylitis.",
#     "Abdominal pain that improves with eating may point to duodenal ulcer, while pain that worsens with eating suggests gastric ulcer.",
#     "Rebound tenderness and pain at McBurney's point are classic signs of appendicitis.",
#     "Pain in the upper right abdomen after fatty meals and positive Murphy’s sign may indicate gallstones."
# ]
# 
# embedder = SentenceTransformer('all-MiniLM-L6-v2')
# doc_embeddings = embedder.encode(docs, convert_to_numpy=True)
# index = faiss.IndexFlatL2(doc_embeddings.shape[1])
# index.add(doc_embeddings)
# 
# generator = pipeline("text2text-generation", model="google/flan-t5-base")
# 
# def retrieve_context(query, k=2):
#     query_embedding = embedder.encode([query], convert_to_numpy=True)
#     _, I = index.search(query_embedding, k)
#     return " ".join([docs[i] for i in I[0]])
# 
# def get_answer(context, question):
#     prompt = f"""Based on the following health context, provide a helpful answer to the user's question.
# 
# Context: {context}
# 
# User's Question: {question}"""
#     return generator(prompt, max_length=100)[0]['generated_text']
# 
# user_input = st.text_input("🔍 Ask your question:")
# 
# if user_input:
#     context = retrieve_context(user_input)
#     response = get_answer(context, user_input)
# 
#     st.subheader("💬 Answer:")
#     st.success(response)
# 
#     with st.expander("🧠 Retrieved Knowledge Base Context"):
#         st.write(context)
# 
# st.markdown("---")
# st.markdown("⚠️ *This is not medical advice. For serious conditions, consult a doctor.*")
# '''
# 
# with open("app.py", "w") as f:
#     f.write(code)
# 
# print("✅ Saved as app.py")
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# from google.colab import files
# files.download("app.py")
# 
# 
# 
# 
# 
# req = '''
# streamlit
# faiss-cpu
# sentence-transformers
# transformers
# torch
# '''
# 
# with open("requirements.txt", "w") as f:
#     f.write(req)
# 
# files.download("requirements.txt")
# 
# 
# 
# 
# 
# %%writefile run.py
# from pyngrok import ngrok
# import os
# 
# public_url = ngrok.connect(8501)
# print(f"App is running at: {public_url}")
# 
# os.system("streamlit run app.py")
# 
# 
# 
# !pip install streamlit pyngrok
# !ngrok config add-authtoken 2wqcLWAIasEz53ZeyeCAS24bCTU_4ans5hdgsqQ6h2MAwgfFg
# 
# Or  my
# !pip install streamlit pyngrok
# !ngrok config add-authtoken 2wqjKZ5bndlbhIAr8n6dGr7axce_25Y5nzjRYUFsVa7pjg8v9
# 
# 
# !python run.py
# 
# 
# 
# https://dccb-34-125-3-30.ngrok-free.app/
# https://colab.research.google.com/drive/1cInKh_pmmwwAgC2t1eovtavw89hGwTMZ#scrollTo=luKz1jBNHpoU
#